const constants = {
    SET_BUTTON:"SET_BUTTON",
    SET_TIDIV:"SET_TIDIV",
    SET_NNDIV:"SET_NNDIV",
    SET_PREDDIV:"SET_PREDDIV",
    SET_AGE:"SET_AGE",
    SET_SEX:"SET_SEX",
    SET_MARTIALSTATUS: "SET_MARTIALSTATUS",
    SET_SALARY:"SET_SALARY",
    SET_NUMBEROFINSTANCES: "SET_NUMBEROFINSTANCES",
    SET_K: "SET_K"
}

export  default constants;